#swagger config

springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui


#security:
#  oauth2:
#    client:
#      client-id: first-client
#      client-secret: noonewilleverguess

logging:
  level:
    root: INFO
    org.springframework.security: TRACE
